### ISSUE TITLE
thoughts on how to make this secure, but updatable

### ISSUE THREAD

**Issue by dominictarr** [feross/infinite-app-cache#1]
So, I have been thinking about this.

Basically, this approach successfully disables "network boot", and gives the user confidence a chance to audit the code (especially code that runs crypto)

here is my ideas:
1. appcache starts a "bootloader"
2. bootloader creates a script tag, which runs the hypervisor
3. hypervisor can create apps inside iframes/tabs, using data url if you want.

You could update the bootloader by holding down a key when you load the page (!)
and it would skip the default boot sequence, and give you some options, such as the ability to view the code, and paste new hypervisor code into a text area... (which gets saved in localStorage)

Maybe just have a sha1 in the bootloader, so that it can verify the hashes of code that it loads... of course, you'd want to keep the bootloader as minimal as possible.

**Comment by feross** [comment]
This is great! I think we could use iframes to good effect here to achieve isolation between the apps and the bootloader.

@dcposch - is this something you think would benefit Scramble.io?

**Comment by dominictarr** [comment]
There is one limitation to iframes that must be mentioned.
You are still on the same event loop,
so vulnerable to infinite loops, and things like exponential time regular expressions, etc
https://github.com/substack/safe-regex

So, this method is not suitable for untrusted apps, but it would be fine for your own app.

**Comment by pfrazee** [comment]
I like this idea. The mechanism for updating the bootloader is the biggest question mark for me. It would need to only occur when both the bootloader script and the user authorize it, and be initiated (but not authorized) by the origin host. Possible without involving the vendors?

**Comment by dominictarr** [comment]
@pfraze hmm, I think if you cleared the cache you'd get a new version, but that is not secure.

You need minimal loader, which loads a more sophisticated, but mostly trusted version manager (the "OS").
then that loads apps.

I think you are gonna have to have some part which is never updated, you could make that smaller,
or you could make it larger.

The smallest I think you could have, is a hash algorithim + "OS" code & expected hash as local storage data. Of course, if someone XSS's that domain they can change the bootloader, so never host anything else on that domain - though I think the infinite app cache might handle that?

you update the "OS" code (rarely), the bootloader is always the same, but is trivial.

**Comment by pfrazee** [comment]
@dominictarr based on what I've read, the user can clear it, or it can be changed by the host (which also includes removing the manifest). My feeling is, if the host can control the manifest without user auth, then appcache doesn't improve on CSP. 

Is there a way to stop the browser from trying to sync with the manifest? My initial thought was offline mode, but that'd be problematic, and Chrome doesn't have it.

**Comment by dominictarr** [comment]
yes, but if you put the mainifest inside the mainfest, the client never re-requests the mainfest, so it's out of the hosts control, unless they retrieve it with javascript.

**Comment by pfrazee** [comment]
Aha! That's what I was missing. (Sorry for being thick.) OK, that seems sound enough to dig further.
1. Assuming it does work, I'd be inclined to include a small but complete crypto API. http://bitwiseshiftleft.github.io/sjcl/ maybe, though I didn't see any sign of asymmetric encryption in there.
2. The script loader would, I suppose, XHR-fetch the script, hash it, compare to a hash in localStorage, then load if `==`. If `!=` or fresh (no hash in ls) then Change Detection triggers. There's a lot of techniques you could try to verify the change:
   - You could fetch "update manifests" from multiple HTTPS sources. The upmans might include the old SHA, the new SHA, and a text-file description of changes for the user.
   - You could diff the file for the user, but minification would cause issues.

**Comment by dominictarr** [comment]
under this model, minification isn't a problem, since the js is nearly always cached.
if you want humans to review the changes you shouldn't minify it.

**Comment by feross** [comment]
see http://hyperboot.org/
