### ISSUE TITLE
doesn't work on localhost - run on domain or edit /etc/hosts

### ISSUE THREAD

**Issue by dominictarr** [feross/infinite-app-cache#3]
was testing this,
found that this doesn't work on localhost,
but when I changed `/etc/hosts` so I could type a domain name, but get locahost that did work.

**Comment by feross** [comment]
Interesting... So `http://localhost:xxxx` didn't work for you? I wouldn't be surprised if `file:///` didn't work, but I don't see what would be wrong with localhost.

**Comment by feross** [comment]
I just tested it.
- `node index.js`
- Open http://localhost:8000 in browser.
- Kill node server
- Refresh page. Still cached.

**Comment by dominictarr** [comment]
ah, ... hmm, okay tested it again. Hmm. okay I think I got confused because I didn't run the index.js
and instead hosted the files with a static server, but you need to set the cache header on the manifest +
serve it with the correct content type.

closing.
